def Route18_2019(): 
    draft = [] 
    draft.append("BITE ME")
    draft.append("Food For Anubis")
    draft.append("O-Dog")
    draft.append("Devil Cows")
    draft.append("Gordon Gekko")
    draft.append("Secret Squirrels")
    draft.append("Franks Tanks")
    draft.append("Fubar")
    draft.append("IronCity")
    draft.append("Have Nots")
    draft.append("Piss & Vinegar")
    draft.append("Domanick Davis")
    draft.append("Domanick Davis")
    draft.append("Piss & Vinegar")
    draft.append("Have Nots")
    draft.append("IronCity")
    draft.append("Fubar")
    draft.append("Franks Tanks")
    draft.append("Secret Squirrels")
    draft.append("Gordon Gekko")
    draft.append("Devil Cows")
    draft.append("O-Dog")
    draft.append("Food For Anubis")
    draft.append("BITE ME")
    draft.append("BITE ME")
    draft.append("Food For Anubis")
    draft.append("O-Dog")
    draft.append("Devil Cows")
    draft.append("Gordon Gekko")
    draft.append("Secret Squirrels")
    draft.append("Franks Tanks")
    draft.append("Fubar")
    draft.append("IronCity")
    draft.append("Have Nots")
    draft.append("Piss & Vinegar")
    draft.append("Domanick Davis")
    draft.append("Domanick Davis")
    draft.append("Piss & Vinegar")
    draft.append("Have Nots")
    draft.append("IronCity")
    draft.append("Fubar")
    draft.append("Franks Tanks")
    draft.append("Secret Squirrels")
    draft.append("Gordon Gekko")
    draft.append("Devil Cows")
    draft.append("O-Dog")
    draft.append("Food For Anubis")
    draft.append("BITE ME")
    draft.append("BITE ME")
    draft.append("Food For Anubis")
    draft.append("O-Dog")
    draft.append("Devil Cows")
    draft.append("Gordon Gekko")
    draft.append("Secret Squirrels")
    draft.append("Franks Tanks")
    draft.append("Fubar")
    draft.append("IronCity")
    draft.append("Have Nots")
    draft.append("Piss & Vinegar")
    draft.append("Domanick Davis")
    draft.append("Domanick Davis")
    draft.append("Piss & Vinegar")
    draft.append("Have Nots")
    draft.append("IronCity")
    draft.append("Fubar")
    draft.append("Franks Tanks")
    draft.append("Secret Squirrels")
    draft.append("Gordon Gekko")
    draft.append("Devil Cows")
    draft.append("O-Dog")
    draft.append("Food For Anubis")
    draft.append("BITE ME")
    draft.append("BITE ME")
    draft.append("Food For Anubis")
    draft.append("O-Dog")
    draft.append("Devil Cows")
    draft.append("Gordon Gekko")
    draft.append("Secret Squirrels")
    draft.append("Franks Tanks")
    draft.append("Fubar")
    draft.append("IronCity")
    draft.append("Have Nots")
    draft.append("Piss & Vinegar")
    draft.append("Domanick Davis")
    draft.append("Domanick Davis")
    draft.append("Piss & Vinegar")
    draft.append("Have Nots")
    draft.append("IronCity")
    draft.append("Fubar")
    draft.append("Franks Tanks")
    draft.append("Secret Squirrels")
    draft.append("Gordon Gekko")
    draft.append("Devil Cows")
    draft.append("O-Dog")
    draft.append("Food For Anubis")
    draft.append("BITE ME")
    draft.append("BITE ME")
    draft.append("Food For Anubis")
    draft.append("O-Dog")
    draft.append("Devil Cows")
    draft.append("Gordon Gekko")
    draft.append("Secret Squirrels")
    draft.append("Franks Tanks")
    draft.append("Fubar")
    draft.append("IronCity")
    draft.append("Have Nots")
    draft.append("Piss & Vinegar")
    draft.append("Domanick Davis")
    draft.append("Domanick Davis")
    draft.append("Piss & Vinegar")
    draft.append("Have Nots")
    draft.append("IronCity")
    draft.append("Fubar")
    draft.append("Franks Tanks")
    draft.append("Secret Squirrels")
    draft.append("Gordon Gekko")
    draft.append("Devil Cows")
    draft.append("O-Dog")
    draft.append("Food For Anubis")
    draft.append("BITE ME")
    draft.append("BITE ME")
    draft.append("Food For Anubis")
    draft.append("O-Dog")
    draft.append("Devil Cows")
    draft.append("Gordon Gekko")
    draft.append("Secret Squirrels")
    draft.append("Franks Tanks")
    draft.append("Fubar")
    draft.append("IronCity")
    draft.append("Have Nots")
    draft.append("Piss & Vinegar")
    draft.append("Domanick Davis")
    draft.append("Domanick Davis")
    draft.append("Piss & Vinegar")
    draft.append("Have Nots")
    draft.append("IronCity")
    draft.append("Fubar")
    draft.append("Franks Tanks")
    draft.append("Secret Squirrels")
    draft.append("Gordon Gekko")
    draft.append("Devil Cows")
    draft.append("O-Dog")
    draft.append("Food For Anubis")
    draft.append("BITE ME")
    draft.append("BITE ME")
    draft.append("Food For Anubis")
    draft.append("O-Dog")
    draft.append("Devil Cows")
    draft.append("Gordon Gekko")
    draft.append("Secret Squirrels")
    draft.append("Franks Tanks")
    draft.append("Fubar")
    draft.append("IronCity")
    draft.append("Have Nots")
    draft.append("Piss & Vinegar")
    draft.append("Domanick Davis")
    draft.append("Domanick Davis")
    draft.append("Piss & Vinegar")
    draft.append("Have Nots")
    draft.append("IronCity")
    draft.append("Fubar")
    draft.append("Franks Tanks")
    draft.append("Secret Squirrels")
    draft.append("Gordon Gekko")
    draft.append("Devil Cows")
    draft.append("O-Dog")
    draft.append("Food For Anubis")
    draft.append("O-Dog")
    draft.append("BITE ME")
    draft.append("Food For Anubis")
    draft.append("BITE ME")
    draft.append("Devil Cows")
    draft.append("Gordon Gekko")
    draft.append("Secret Squirrels")
    draft.append("Franks Tanks")
    draft.append("Fubar")
    draft.append("IronCity")
    draft.append("Have Nots")
    draft.append("Piss & Vinegar")
    draft.append("Domanick Davis")
    return(draft)
